Fofura
ThundeRatz/STM32ProjectTemplate pull request #10
Opened 2019-03-15 01:27 UTC by erickotsuka

2019-03-18 23:47 UTC, d-nery requested changes

2019-03-18 23:47 UTC, d-nery commented on README.md
> +## Adding a submodule
Põe antes do debug que é em breve hahaha

2019-03-19 00:14 UTC, d-nery approved these changes

2019-03-21 17:44 UTC, freitas-renato commented on README.md
> +## Adding a submodule
Não é melhor deixar em português igual o resto do readme?

2019-03-21 17:45 UTC, d-nery commented on README.md
> +## Adding a submodule
Justo haahah

2019-03-21 18:40 UTC, erickotsuka commented on README.md
> +## Adding a submodule
Eita. Nem percebi ~porque sou muito bilíngue~.

2019-03-22 20:36 UTC, erickotsuka commented
E aí? Merge?

2019-03-23 12:42 UTC, freitas-renato approved these changes

2019-03-23 14:15 UTC, erickotsuka commented
Ops, não dá merge ainda rs

2019-03-23 16:08 UTC, d-nery requested changes

2019-03-23 16:08 UTC, d-nery commented on Makefile
> +UNCRUSTIFY_FILES = $(C_SOURCES) $(wildcard */*.h)
find, sei lá se aqui tem mais de um nível de pasta

2019-03-23 16:08 UTC, d-nery commented on inc/mcu.h
> +#endif /* __MCU_H__ */
Ah não, tira essa regra do uncrustify tbm hahaha é muito chata

2019-03-23 16:08 UTC, d-nery commented on Makefile
> +.uncrustify/%: %
Entendi nada mas acredito

2019-03-23 16:14 UTC, erickotsuka commented on Makefile
> +.uncrustify/%: %
Só explicando. O uncrustify cria um outro arquivo com as correções de formatação. Aí cria na pasta .uncrustify e depois copia de volta pro lugar certo. Depois, apaga a pasta uncrustify. E não dá pra passar uma lista de arquivos, é um arquivo por vez.

2019-03-24 01:06 UTC, d-nery commented on Makefile
> +.uncrustify/%: %
uashuash ok

2019-03-24 18:30 UTC, d-nery commented
Ou, tem que tirar o clang-format dos requisitos então, e adicionar o uncrustify

2019-03-26 01:26 UTC, freitas-renato approved these changes
Parece estar tudo certo.

2019-03-26 23:53 UTC, erickotsuka commented
Testei no Windows com MSYS2 e funcionou as coisas do uncrustify.

2019-03-27 17:37 UTC, d-nery approved these changes

2019-03-27 17:46 UTC, merged