Mais mudancinhas
ThundeRatz/STM32ProjectTemplate pull request #14
Opened 2019-06-13 22:45 UTC by d-nery

Colocamos arquivos de config do vs code com parâmetros que dependem do projeto e de devices para serem gerado pelo Makefile (no make prepare)

Separamos a parte de cima do Makefile num config.mk, assim, só esse arquivo precisa ser modificado, isso é para ficar mais fácil de atualizar o Makefile em outros projetos quando o do template atualizar (aí é só sobrescrever o arquivo sem se preocupar em mudar de novo os defs)

2019-06-13 23:19 UTC, LucasHaug approved these changes

2019-06-14 12:36 UTC, freitas-renato commented
Seria legal mudar o README falando pra alterar os parâmetros no .mk agora

2019-06-14 12:37 UTC, freitas-renato requested changes
Seria legal mudar o README falando pra alterar os parâmetros no .mk agora

2019-06-15 16:20 UTC, freitas-renato approved these changes

2019-06-16 14:40 UTC, merged