Develop
ThundeRatz/STM32ProjectTemplate pull request #22
Opened 2020-01-25 14:45 UTC by LucasHaug

2020-01-27 22:47 UTC, d-nery requested changes

2020-01-27 22:47 UTC, d-nery commented on Makefile
>  TEST_SOURCES := $(shell find $(TEST_DIR)/src -name "*.c")
Aqui nao vai dar o msm warning?

2020-01-27 23:48 UTC, LucasHaug commented on Makefile
>  TEST_SOURCES := $(shell find $(TEST_DIR)/src -name "*.c")
Eh, ~~a gente já conversou, mas falando aqui~~ tem o `test_main.c` lá o o `src` já existe, então aí não dá warning, então dá pra fazer o que você sugeriu pessoalmente de fazer a pasta `inc` existir e colocar um arquivo lá só pra fazer a pasta existir.

2020-01-28 05:47 UTC, d-nery approved these changes

2020-01-29 04:27 UTC, merged