✔️ Atualização da metodologia de testes
ThundeRatz/STM32ProjectTemplate pull request #26
Opened 2021-04-15 03:20 UTC by LucasHaug

Entonces, um problema que a gente tava tendo desenvolvendo o código da Galena é que a gente tava fazendo vários testes de várias cosas, mas a gente só tinha uma main de testes, aí tinha que ficar mudando a main toda hora o que não faz sentido. Pensando nisso venho propor uma mudança na forma que a gente faz os teste, se assemelhando na forma como a gente faz as coisas no ThunderVolt, por exemplo de criar vários executáveis de teste e rodar eles pra testar coisas independentes umas das outras.

Essa PR resolveria a issue #25.

2021-04-15 11:59 UTC, FelipeGdM commented
Sucesso total, altamente promissor

Senti falta de algum tipo de feedback indicando qual o teste que foi compilado, o único momento que a varável `TEST_NAME` é utilizada é pra buscar o arquivo .c, nem no nome do arquivo `.elf` tem o nome do teste que foi compilador. Tem 100% de chance de alguém gravar um teste pensando que tá gravando outro :stuck_out_tongue_closed_eyes: 

Outra sugestão que eu faria é compilar e gerar os `.hex` de todos os testes e só selecionar qual teste utilizar na hora de gravar no MCU. Isso agiliza a brincadeira se quiser fazer vários testes de validação em série. Como os testes são independentes, é safe de gerar o `.hex` de todo mundo ao msm tempo

Bastaria utilizar um coringa de Makefile pra fazer isso, algo assim

```make
# The .elf file depend on all object files and the Makefile
$(BUILD_DIR)/test_$(PROJECT_NAME)_%.elf: $(TEST_DIR)/%.c $(OBJECTS) $(CUBE_OBJECTS) $(LIB_OBJECTS) config.mk Makefile | $(BUILD_DIR)
```

A primeira sugestão é mais crítica e a segunda é mais estética, fica aí a cargo do leitor decidir o que fazer

No mais, fiquem bem e mantenham-se hidratados

2021-04-15 12:01 UTC, FelipeGdM commented on Makefile
> +TEST_OBJECT := $(addprefix $(BUILD_DIR)/$(TEST_DIR)/,$(notdir $(CURRENT_TEST_SOURCE:.c=.o)))
```suggestion
TEST_OBJECT  := $(addprefix $(BUILD_DIR)/$(TEST_DIR)/,$(notdir $(CURRENT_TEST_SOURCE:.c=.o)))
```

2021-04-15 12:37 UTC, d-nery commented on Makefile
> -TEST_HEADERS := $(shell find $(TEST_DIR)/inc -name "*.h")
Mas pra onde foram os .h??

2021-04-15 12:50 UTC, LucasHaug commented on Makefile
> -TEST_HEADERS := $(shell find $(TEST_DIR)/inc -name "*.h")
Não existem mais headers de arquivos de testes huasahsuahuashush

2021-04-15 12:54 UTC, d-nery commented
Umas coisas, desse jeito, pelo que entendi, cada teste só pode ser um único arquivo, então se você quiser um teste mais complexo, não poderia separar e faria um arquivo enorme, minha sugestão é por uma nova pasta (pode ser "bin"), onde ficariam os arquivos com as mains, e na src deixa as partes separadas ou "em comum", até pq diferentes mains poderiam reutilizar uma parte do teste.

```make
CURRENT_TEST_SOURCE := $(shell find $(TEST_DIR)/bin -name $(TEST_NAME).c)

TEST_HEADERS := $(shell find $(TEST_DIR)/inc -name "*.h")
TEST_SOURCES := $(shell find $(TEST_DIR)/src -name "*.c")

TEST_OBJECTS := $(addprefix $(BUILD_DIR)/$(TEST_DIR)/,$(notdir $(TEST_SOURCES:.c=.o)))
TEST_OBJECTS += $(addprefix $(BUILD_DIR)/$(TEST_DIR)/,$(notdir $(CURRENT_TEST_SOURCE:.c=.o)))

# Desfazer todo o resto das mudanças que envolvem TEST_HEADERS e etc

# The .elf file depend on all object files and the Makefile
$(BUILD_DIR)/$(TEST_NAME)_$(PROJECT_NAME).elf: $(OBJECTS) $(TEST_OBJECT) $(CUBE_OBJECTS) $(LIB_OBJECTS) config.mk Makefile | $(BUILD_DIR)
```

Obviamente não testei nada que escrevi aqui, veio de cabeça, então tenta rodar antes caso eu tenha errado alguma coisa

Mas assim diria que fica mais organizado, na segunda parte ali daria pra usar a sugestão do Felipe pra sempre compilar todos, mas as vezes um teste pode não estar funcionando e você não quer mexer nele no momento, então assim vai sempre só o que vc quer (e só vai recompilar a main msm, os outros obj que são comuns vão estar compilados)

2021-04-17 00:23 UTC, LucasHaug commented
Entonces não fiz a parte de compilar todos os testes ao mesmo tempo,porque seria bem mais role, factível, mas mais role e acho que não precisa, porque tendo compilado a parte do cube e todas as partes comuns, compilar cada teste é muito rápido, aí bom de compilar separado é que você só compila o que você quer e garante que esse tá funcionando.

2021-04-19 23:53 UTC, GabrielKishida commented on tests/bin/test_main.c
> +    test_core_init();
Pode ser uma pergunta tosca, mas pq???

Tipo, eu entendo que você tá modularizando e fazendo os testes receberem somente coisas do test_core, mas se tudo que tem dentro do test_core é o próprio mcu_init, pq fazer isso?

2021-04-19 23:56 UTC, GabrielKishida commented on tests/bin/test_main.c
> +    test_core_init();
Okay, acho que entendi o pq, considerando que se trata de um template.

Nao sei quao comum é a necessidade de fazer um test_core_init() para inicializar coisas que sao comuns a todos os testes, mas imagino que deve ser razoavelmente comum.

Deixa, me auto-respondi eu acho.

2021-04-20 00:04 UTC, GabrielKishida approved these changes
Assim, grande parte das coisas eu posso ter olhado mal pois eu tenho absolutamente 0 conceitos prévios de makefile.

No entanto, dei uma olhada nos arquivos alterados e pelo que eu vi, grande parte das coisas foram algumas mudanças nos nomes de variáveis, e diretórios -- para receber as coisas como parâmetros e mudando para compilar os testes com os diferentes comandos do make.

Só uma pergunta meio batata, que nao muda muito: se você nao fez a compilacao simultanea da varios testes, porque que você deixou o nome das variáveis no plural? tipo:

``` make
TESTS_HEADERS := $(shell find $(TEST_DIR)/inc -name "*.h")
```
Se os testes simultaneos nao tao sendo compilados todos ao mesmo tempo, melhor deixar no singular, nao?

Bom mas isso é só estética. De resto tá aprovado.

2021-04-20 00:50 UTC, DamaralHenrique approved these changes
Me parece que está tudo certo!

2021-04-20 01:23 UTC, FelipeGdM approved these changes

2021-04-20 01:24 UTC, febagni commented on tests/bin/test_main.c
> +    test_core_init();
Modularização, meu amigo

2021-04-20 01:25 UTC, febagni commented on tests/bin/test_main.c
> +    test_core_init();
Assim, dá pra add coisas novas dentro do ```test_core_init()```

2021-04-20 01:26 UTC, febagni commented on README.md
> +O diretório definido pela variável `TEST_DIR` contém arquivos para testes de partes específicas do projeto, separando isso do código do proejto em si. Esses arquivos devem ser implementados de acordo
```suggestion
O diretório definido pela variável `TEST_DIR` contém arquivos para testes de partes específicas do projeto, separando isso do código do projeto em si. Esses arquivos devem ser implementados de acordo com as necessidades dos desenvolvedores. 
```

2021-04-20 01:28 UTC, febagni requested changes
Só dei request pra arrumar a palavra lá asuhduahsdua

2021-04-20 01:32 UTC, febagni approved these changes
Arrumei logo haushdauhda

2021-04-20 01:39 UTC, merged