✨ Include general config header in Makefile
ThundeRatz/STM32ProjectTemplate pull request #31
Opened 2022-02-27 17:40 UTC by LucasHaug

A gente tinha criado o diretório de arquivos de configuração, mas do jeito que tava, a gente só tinha a opção de adicionar configurações de placa, não de outras coisas, então mudei pra incluir os outros header que possam estar no diretório de configuração.

2022-03-06 22:09 UTC, lucastrschneider commented on Makefile
> +CFLAGS += $(C_GENERAL_CONFIG_INCLUDES)
Só comentando que desse jeito a gnt tem que de fato incluir no código os arquivos dentro da pasta cfg né? Não sei se a ideia era pra ser assim mesmo, mas é pq os de config de placa a gnt não inclui explicitamente, ai não sei direito o que é melhor. Acho que se for pra incluir manualmente, daria para deixar direto dentro de inc/, e não nesse diretório especial, mas acho que vale a discussão

2022-03-11 11:45 UTC, LucasHaug commented
Mudei agora pra que os headers na pasta cfg sejam adicionados sem precisar dar `#include`, além disso também arrumei o target do Makefile de gerar os arquivos de configuração do VSCode pra incluir esses arquivos de configuração, pro Intellisense não dar erro.

2022-03-12 16:32 UTC, lucastrschneider requested changes

2022-03-12 16:32 UTC, lucastrschneider commented on Makefile
> +	$(AT)rm $(VS_C_CPP_PROPERTIES_FILE)
aqui ta dando erro acho, se você nunca gerou antes ele não tem como remover pq os arquivos ainda não existem, tem que ver certinho como fazer pra ele atualizar dps de ja ter sido gerado

2022-03-12 17:15 UTC, VanderSant approved these changes
Muito top, @LucasHaug !
Eu testei tudo no repositório da TPM-Galena e funcionou direitinho

2022-03-12 17:40 UTC, lucastrschneider approved these changes
sucesso dms

2022-03-12 17:45 UTC, merged