Migra o template para CPP
ThundeRatz/STM32ProjectTemplate pull request #46
Opened 2023-10-21 18:20 UTC by Eduardo-Barreto

Com o recente movimento de migração dos códigos da equipe para C++ e a criação das libs, acho que faz total sentido migrarmos esse template aqui também, tanto para facilitar a criação de novos projetos quanto para os testes da lib mesmo

# O que foi feito?
- Mudanças no `CMakeLists.txt` pra compilar em C++ (bem trivial)
- Migração do MCU, main e testes para C++

2023-10-21 18:24 UTC, Eduardo-Barreto commented
Ah, só uma coisa, existe uma [branch antiga de migração](https://github.com/ThundeRatz/STM32ProjectTemplate/tree/feature/migrate_cpp), mas fui orientado na gaiola de simplesmente abrir outra (desculpa xin)

2023-10-21 19:55 UTC, n-honda2 approved these changes
Acho q tá td check, vc falou q compilou certinho então sucesso

2023-10-22 03:13 UTC, Bruno1406 requested changes
Para além dos comentários q eu fiz, fiquei preocupado se nn faltou isso aqui no cmake
![Screenshot from 2023-10-22 00-13-27](https://github.com/ThundeRatz/STM32ProjectTemplate/assets/112660250/5f855f9e-90ab-4184-8244-1cb5c5d31507)
 Nn manjo nada dessas opções de linker nn, mas foi só com elas que eu consegui buildar a lib de IMU.

2023-10-22 03:13 UTC, Bruno1406 commented on CMakeLists.txt
> +file(GLOB_RECURSE C_HEADERS CONFIGURE_DEPENDS "inc/*.hpp")
```suggestion
file(GLOB_RECURSE C_SOURCES CONFIGURE_DEPENDS "src/*.cpp" "src/*.c")
file(GLOB_RECURSE C_HEADERS CONFIGURE_DEPENDS "inc/*.hpp" "inc/*.h)
```
Acredito eu que o template, por ser bem genericão, ainda deva suportar C. Pode ser que precisemos por algum motivo de alguns arquivos em C, ou pode ser que num futuro seja mais adequado se utilizar de C para algum projeto. No fim do dia, não  faz mal manter o suporte para C.

2023-10-22 03:13 UTC, Bruno1406 commented on CMakeLists.txt
> +file(GLOB_RECURSE TESTS_BIN CONFIGURE_DEPENDS "tests/bin/*.cpp")
```suggestion
file(GLOB_RECURSE TESTS_SOURCES CONFIGURE_DEPENDS "tests/src/*.cpp" "tests/src/*.c")
file(GLOB_RECURSE TESTS_HEADERS CONFIGURE_DEPENDS "tests/inc/*.hpp" "tests/inc/*.h")
file(GLOB_RECURSE TESTS_BIN CONFIGURE_DEPENDS "tests/bin/*.cpp" "tests/bin/*.c")
```

2023-10-22 03:13 UTC, Bruno1406 commented on inc/mcu.hpp
> +extern "C"
```suggestion
```
Esse 'extern "C" ' aí nn tá fazendo nada. Esse arquivo nn é compatível com c de jeito nenhum por causa do namespace e da definição de claase. Agora, se o intuito for fazer ele ficar compatível com C, tem que tirar o namespace, matar a classe e adicionar um 
#ifdef __cpluplus
extern "C" {
#endif   
Vou deixar um [link](https://isocpp.org/wiki/faq/mixing-c-and-cpp) aqui para curiosidade, falando um pouco sobre

2023-10-22 03:13 UTC, Bruno1406 commented on inc/mcu.hpp
> +    class mcu
Isso aqui é só um comentário. Nn sei se vejo muito sentido nisso aqui ser uma classe nn. Se a ideia for encapsulamento, "mcu" poderia ser um namespace. Por outro lado, eu entendo que está seguindo um padrão e piriri pororó.

2023-10-22 03:13 UTC, Bruno1406 commented on src/mcu.cpp
>  #include "main.h"
```suggestion
#include "main.h"

namespace hal {
```
Como aqui a gente só tá definindo a classe que tá dentro do namespace, acho bem suave de fazer isso daqui.

2023-10-22 03:13 UTC, Bruno1406 commented on src/mcu.cpp
> +void hal::mcu::init(void)
```suggestion
void mcu::init(void)
```

2023-10-22 03:13 UTC, Bruno1406 commented on src/mcu.cpp
> +void hal::mcu::sleep(uint32_t ms)
```suggestion
void mcu::sleep(uint32_t ms)
```

2023-10-22 03:13 UTC, Bruno1406 commented on src/mcu.cpp
> +void hal::mcu::led_toggle(void)
```suggestion
void mcu::led_toggle(void)
```

2023-10-22 03:13 UTC, Bruno1406 commented on src/mcu.cpp
>  }
```suggestion
}
} // namespace hal
```

2023-10-22 19:27 UTC, Eduardo-Barreto commented on inc/mcu.hpp
> +extern "C"
então, ele ta aí pq essa `SystemClock_Config` é uma função definida pelo Cube, e como ela ta sendo chamada pela classe de mcu, o código n compila sem esse extern

2023-10-22 19:28 UTC, Eduardo-Barreto commented on inc/mcu.hpp
> +    class mcu
po foi 100% pelo padrão

a ideia era manter como nas futuras libs, mcu ser uma classe no namespace hal

2023-10-22 20:37 UTC, Erick-DAS approved these changes
Só deixei uma pergunta sobre padrões ali no CMake, mas fora isso parece tudo check

2023-10-22 20:37 UTC, Erick-DAS commented on CMakeLists.txt
> +file(GLOB_RECURSE TESTS_BIN CONFIGURE_DEPENDS "tests/bin/*.cpp" "tests/bin/*.c")
Só uma dúvida besta aqui de padrão do CMake, faz sentido msm a gente manter os nomes `C_SOURCES` e  `C_HEADERS` agora que é C++? Ao invés de `CPP_SOURCES` por exemplo. 

Já que vamos manter também os arquivos `.c` e `.h` compiláveis, nesse caso teria que ter ambos os `C_SOURCES` e `CPP_SOURCES` ai moh trampo né kkkkk.

Enfim, sei que não faz diferença, perguntando só pra saber mesmo.

2023-10-23 12:49 UTC, Eduardo-Barreto commented on CMakeLists.txt
> +file(GLOB_RECURSE TESTS_BIN CONFIGURE_DEPENDS "tests/bin/*.cpp" "tests/bin/*.c")
você tem um bom ponto! Eu particularmente acho que não vai ter diferença entre `C_SOURCES` e `CPP_SOURCES` tirando o nome, então talvez algo como `PROJECT_SOURCES` faça mais sentido

2023-10-23 12:50 UTC, Erick-DAS commented on CMakeLists.txt
> +file(GLOB_RECURSE TESTS_BIN CONFIGURE_DEPENDS "tests/bin/*.cpp" "tests/bin/*.c")
Gostei da ideia, apoio

2023-10-27 13:07 UTC, LucasHaug commented on inc/mcu.hpp
> +{
~~O uncrustify deixa essa chave aqui mesmo? Estranho ahushuashuashu~~

2023-10-27 13:07 UTC, LucasHaug commented on inc/mcu.hpp
> +namespace hal {
Então, não sei sobre deixar esse namespace hal aqui, acho que pode deixar mais simples pro template. Não é porque existem namespaces que a gente tem que colocar vários, tem que saber dosar. Mas assim batata também.

2023-10-27 13:07 UTC, LucasHaug commented on inc/mcu.hpp
> +class mcu {
Tenho alguns mixed feeling sobre deixar isso como classe no template. Tipo não é porque suporta classe que a gente tem que usar classe em tudo. O sleep e o init até fazem sentindo estarem numa classe assim, tanto que eles já tinham o prefixo do `mcu_`, mas aí o led toggle deixa meio estranho. Como não tem muito também onde colocar, batata também ahushuauahas.

Esse e o comentário do namespace são meio batatas, é só pra pensarem quando tiverem as coisas de usar com moderação as features da linguagem.

2023-10-27 13:07 UTC, LucasHaug commented on inc/mcu.hpp
> +#define __MCU_H__
```suggestion
#ifndef __MCU_HPP__
#define __MCU_HPP__
```

2023-10-27 13:07 UTC, LucasHaug commented on inc/mcu.hpp
> +#endif // __MCU_H__
```suggestion
#endif // __MCU_HPP__
```

2023-10-30 23:04 UTC, Eduardo-Barreto commented on inc/mcu.hpp
> +{
aisduhas de fato estranho, mas o make format nao mudou isso aí

2023-10-30 23:16 UTC, Eduardo-Barreto commented on inc/mcu.hpp
> +class mcu {
o sleep e o init foram por esse motivo q vc citou, o led_toggle eu imaginei que se referia ao led da placa asudhasiudh no caso da bluepill é o C13, mas no código estar o A5 deixa mais esquisito mesmo asduihasiu

2023-10-30 23:17 UTC, Eduardo-Barreto commented on inc/mcu.hpp
> +namespace hal {
ah, na minha cabeça fazia sentido (principalmente considerando as libs), só botei pq nao vi pq nao botar sinceramente

2023-11-06 19:41 UTC, pedroazeredo04 reviewed
Cara eu boto fé, achei bem legal do jeito que tá, com namespace pras coisinhas do HAL e tals. 

Idealmente, essa abstração das funções do HAL viriam de uma lib?

2023-11-06 19:41 UTC, pedroazeredo04 commented on inc/mcu.hpp
> +namespace hal {
Acho que eu gosto de um namespace hal, ele ajuda a segmentar o que é baixo do que é alto. Se algo tem escrito `hal::` antes, a gente sabe que é uma abstração de algo bem baixo nível, coisa de função da ST.

2023-11-06 19:41 UTC, pedroazeredo04 commented on inc/mcu.hpp
> +class mcu {
Também tenho mixed feelings mas acho que tem que ficar como classe sim. Na minha opinião, numa alternativa sem classe, ficaria meeeio estranho de acessar, ficaria algo do tipo `hal::sleep(50)`, daí ainda mais com RTOS, é um sleep do HAL? É um Sleep do RTOS? Sei lá asdhuadhuasd acho que `hal::mcu::sleep(50)` é mais bonito.

2023-11-06 19:59 UTC, Eduardo-Barreto commented
> @pedroazeredo04:  Idealmente, essa abstração das funções do HAL viriam de uma lib?

não sei se entendi o que vc quis dizer, é sobre as `HAL_*` dentro das funções no mcu? se sim, fiquei meio confuso de como fazer isso sem obrigar quem for usar o template de usar nossas libs (tudo bem que seria só mudar esse arquivo mas sei la asudhausdh) e coloquei direto as funções do hal, mas é mutável pra deixar com a lib se for o caso, como o led_toggle usar a gpio, apesar de ficar meio alubaubdsalub sobre isso kkkkkkkk na minha cabeça tudo bem a galera que ta no namespace `hal` usar o hal da st mas entendo o ponto

2024-02-23 13:27 UTC, Eduardo-Barreto commented
Revendo aqui, removi o `led_toggle` do mcu pq realmente não faz muito sentido auihashdauis mas acho que de resto ta tudo check

2024-02-23 13:36 UTC, LucasHaug commented
Não revisei de novo agora, mas antes de dar merge de qualquer coisa, acho que seria bom fazer umas releases e atualizações. Primeiro diria pra fechar a PR #37 e aí fazer uma release da main com a versão final do projeto com Makefile, aí diria pra fazer merge da develop na main com as coisas de CMakeLists e aí fazer outra release. Aí acho que dá pra ver de mergear essa PR na develop, só pra gente ter os estágios das coisas diferentes salvos em releases e as coisas não se misturarem de uma vez e a PR da develop pra main virar um monstro.

2024-02-23 20:11 UTC, Eduardo-Barreto commented
Top top @LucasHaug, a ideia era mergear as coisas atuais pra develop e depois mandar pra main mesmo, mas não tinha pensado no release, vou fazer aqui

sobre essa outra PR, ia comentar AGORA aqui na gaiola pra fechar ela, inclusive vi esse seu comentário aqui pq vim de lá kkkkk

2025-03-17 04:10 UTC, Eduardo-Barreto commented
opa, a #50 resolve isso!

2025-03-17 04:10 UTC, closed without merging